openapi : 3.0.0

info:
     title: Learn Express and Swagger -LearnCodeOnline
     description: LCO - a course Segment About write docs
     version: 1.0.0
     contact:
       email : sundar@google.com
       url : "https://github.com/Sundarleo11"
     
servers: 
- url: "{protocol}://localhost:5000/api/{version}"
  description: Development server for local Host
  variables:
   version:
    enum:
     - v1
     - v2
   protocol:
    enum:
    - http
    - https